export const MESSAGES = {
  AUTH: {
    UNAUTHENTICATED: "Username or password is invalid",
    USERNAME_INVALID: "Username is required",
    PASSWORD_INVALID: "Password is required",
    PASSWORD_TOO_SHORT: "Password must be at least 6 characters",
    CONFIRM_PASSWORD: "Confirm password is required",
    CONFIRM_PASSWORD_INVALID: "Passwords do not match",
    AUTH_SUCCESSFUL: "Login successful",
    NAME_INVALID: "Name is required",
    NAME_TOO_SHORT: "Name must be at least 2 characters long",
    EMAIL_INVALID: "Email is required",
    EMAIL_INVALID_FORMAT: "Invalid email address",
    PHONE_INVALID: "Phone number is required",
    PHONE_INVALID_FORMAT: "Phone number is required",
    REGISTER_SUCCESSFUL:
      "Register successful. Please check your email to activate your account",
    REGISTER_FAILED: "Register failed",
    ACTIVE_ACCOUNT_FAILED: "Active account failed",
    FORGOT_PASSWORD: "Please check your email to reset password",
    FORGOT_PASSWORD_FAILED: "Forgot password failed",
    RESET_PASSWORD_FAILED: "Reset password failed",
    RESET_PASSWORD_SUCCESSFUL: "Reset password successful",
  },
};
